[package]
name = "windmill-deno"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "windmill_deno"
path = "src/lib.rs"

[dependencies]
deno.workspace = true
deno_lockfile.workspace = true
deno_runtime.workspace = true
tracing-log.workspace = true
futures.workspace = true
anyhow.workspace = true
deno_core.workspace = true
deno_ast.workspace = true
deno_graph.workspace = true
tokio.workspace = true
deadpool.workspace = true
async-trait.workspace = true

[target.'cfg(unix)'.dependencies]
unix-named-pipe.workspace = true

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports", "async_tokio"] }

[[bench]]
name = "single_job"
harness = false
